In [2]:
import numpy as np

In [3]:
#Loading Dataset
banknote=np.genfromtxt('data_banknote_authentication.txt',delimiter=',')


In [4]:
banknote

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
def draw_rand_label(x, label_list):
    seed = abs(np.sum(x))
    while seed < 1:
        seed = 10 * seed
    seed = int(1000000 * seed)
    np.random.seed(seed)
    return np.random.choice(label_list)


# Part 1

In [11]:
# Q1. feature_means
def feature_means(self,banknote):
    features=banknote[:,:4]
    return np.mean(features,axis=0)

In [12]:
# Q2.covariance matrix 4*4 features
def covariance_matrix(self, banknote):
    return np.cov(features.T)


In [13]:
#Q3 Feature means class 1
def feature_means_class_1(self, banknote):
    data_class_1 = banknote[banknote[:,4] == 1, :4]
    return np.mean(data_class_1,axis=0)

In [14]:
#Q4: Covariance matrix class 1
def covariance_matrix_class_1(self, banknote):
    return np.cov(data_class_1.T)

In [15]:
feature_means(banknote)

array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652])

# Part 2

In [375]:
#Part 2- Q1
#implement Random
class HardParzen:
    def __init__(self, h):
        self.h = h
    def train(self, train_inputs, train_labels):
        self.label_list = np.unique(train_labels)
        self.label_length=len(np.unique(train_labels))
        self.train_inputs=train_inputs
        self.train_labels=train_labels
        self.k=50
    def compute_predictions(self, test_data):
        neighbours=[]
        
        length=test_data.shape[0]
        classes_pred=np.zeros(length)
        counts=np.ones((length,self.label_length))
        radius=self.h
        for i in range(len(test_data)):
            
            distance=(np.sum((np.abs(test_data[i] - self.train_inputs)) ** 2, axis=1)) ** (1.0 / 2)
            neighbours = np.array([j for j in range(len(distance)) if distance[j] < radius])
            print()
            for k in neighbours:
                counts[i,int(self.train_labels[k])]+=1
            print(counts)
            if max(counts[i,:])==1:
                classes_pred[i]=draw_rand_label(test_data[i],self.label_list)
            else:
                classes_pred[i] = np.argmax(counts[i, :])
        return classes_pred
#         
         

In [376]:
f=HardParzen(0.01)
test=np.array([[ 3.6216 ,  9.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  7.1674 , -2.4586 , -1.4621 ,  0.     ],
        [-3.5637 ,  -8.3827 ,  11.393  ,  -1.2823 ,   1.]
              ])
f.train(banknote[:1300,:4],banknote[:1300,4])
f.compute_predictions(test[:,:4])


[[1. 1.]
 [1. 1.]
 [1. 1.]]
1.0 [0. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]
0.0 [0. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]
0.0 [0. 1.]


array([1., 0., 0.])

In [222]:
test

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ]])

In [26]:
train=banknote[0:5]
train

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645,  0.     ],
       [ 3.4566 ,  9.5228 , -4.0112 , -3.5944 ,  0.     ],
       [ 0.32924, -4.4552 ,  4.5718 , -0.9888 ,  0.     ]])

In [27]:
test=banknote[5:7]
print(test)
test_label=test[:,4]

[[ 4.3684   9.6718  -3.9606  -3.1625   0.     ]
 [ 3.5912   3.0129   0.72888  0.56421  0.     ]]


In [28]:
train=banknote[0:5]
train_label=train[:,4]

In [29]:
train_label

array([0., 0., 0., 0., 0.])

In [287]:
import numpy as np
import matplotlib.pyplot as plt
N=30
sigma=1
T=np.linspace(1,N,N)
n=30
X=np.random.normal(0, sigma, 1000)
x=1
alpha=0.45

def k_gaussien(x,sigma): #kernel gaussien
    if(sigma<=0):
        return((1/(sigma*sqrt(2*pi)))*exp(-(x**2/(2*sigma**2))))

# def h(n,alpha): #bandwith
#     h=np.ones((1,1))
#     for i in range(2,N):
#         h[i]= h[i-1] + (i**(-alpha))

def f_PR(x,X,sigma): #Parzen-Rosenblatt estimator (f_PR)
    global F;
    F = np.zeros((N,0));
    for k in range(2,N):
        for i in  range(1,k):
            F[k] = F[k-1] + k_gaussien((x-X[i]),1);
        F[k] = F[k-1] 
    print(F);

# almost surely convergency
fPR=f_PR(x,X,sigma)


[]


In [296]:
x=np.array([[1,2],[3,4]])

In [297]:
sigma=1
sig=(1/(np.sqrt(2*np.pi)*sigma))*np.exp(-(x**2/(2*sigma**2)))
print(sig)

[[2.41970725e-01 5.39909665e-02]
 [4.43184841e-03 1.33830226e-04]]


In [307]:
sigma=1
x=
print((1/(sigma*np.sqrt(2*np.pi)))*np.exp(-(x**2/(2*sigma**2))))

0.05399096651318806


In [ ]:
for i in range(len(test_data)):
    distance=(np.sum((np.abs(test_data[i] - self.train_inputs)) ** 2, axis=1)) ** (1.0 / 2)
    

# Part - 4 Split Dataset


In [340]:
def split_dataset(banknote):
    length=list(range(0,len(banknote)))
    train_index=[]
    validation_index=[]
    test_index=[]
    
    for i in range(0,len(length)):
        if i%5==0 or i%5==1 or i%5==2:
            train_index.append(i)
        elif i%5==3:
            validation_index.append(i)
        elif i%5==4:
            test_index.append(i)
    train=banknote[train_index]
    validation=banknote[validation_index]
    test=banknote[test_index]
#     print(len(train),len(validation),len(test))
    return (train,validation,test)
    


In [341]:
temp=split_dataset(banknote)
print(temp)

824 274 274
(array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645,  0.     ],
       ...,
       [ 0.40614,  1.3492 , -1.4501 , -0.55949,  1.     ],
       [-3.5637 , -8.3827 , 12.393  , -1.2823 ,  1.     ],
       [-2.5419 , -0.65804,  2.6842 ,  1.1952 ,  1.     ]]), array([[ 3.4566e+00,  9.5228e+00, -4.0112e+00, -3.5944e+00,  0.0000e+00],
       [ 3.2032e+00,  5.7588e+00, -7.5345e-01, -6.1251e-01,  0.0000e+00],
       [-1.5768e+00,  1.0843e+01,  2.5462e+00, -2.9362e+00,  0.0000e+00],
       ...,
       [-1.0116e+00, -1.9038e-01, -9.0597e-01,  3.0030e-03,  1.0000e+00],
       [-1.1667e+00, -1.4237e+00,  2.9241e+00,  6.6119e-01,  1.0000e+00],
       [-1.3887e+00, -4.8773e+00,  6.4774e+00,  3.4179e-01,  1.0000e+00]]), array([[  0.32924 ,  -4.4552  ,   4.5718  ,  -0.9888  ,   0.      ],
       [  1.5356  ,   9.1772  ,  -2.2718  ,  -0.73535 ,   0.      ],
       [  3.404   ,   8

In [333]:
li=[3,8,13]
temp=banknote[li]
print(temp)

[[ 3.4566   9.5228  -4.0112  -3.5944   0.     ]
 [ 3.2032   5.7588  -0.75345 -0.61251  0.     ]
 [-1.5768  10.843    2.5462  -2.9362   0.     ]]


In [317]:
banknote[0:10]

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645,  0.     ],
       [ 3.4566 ,  9.5228 , -4.0112 , -3.5944 ,  0.     ],
       [ 0.32924, -4.4552 ,  4.5718 , -0.9888 ,  0.     ],
       [ 4.3684 ,  9.6718 , -3.9606 , -3.1625 ,  0.     ],
       [ 3.5912 ,  3.0129 ,  0.72888,  0.56421,  0.     ],
       [ 2.0922 , -6.81   ,  8.4636 , -0.60216,  0.     ],
       [ 3.2032 ,  5.7588 , -0.75345, -0.61251,  0.     ],
       [ 1.5356 ,  9.1772 , -2.2718 , -0.73535,  0.     ]])