In [465]:
import numpy as np

In [752]:
#Loading Dataset
banknote=np.genfromtxt('data_banknote_authentication.txt',delimiter=',')


In [467]:
banknotes

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [468]:
def draw_rand_label(x, label_list):
    seed = abs(np.sum(x))
    while seed < 1:
        seed = 10 * seed
    seed = int(1000000 * seed)
    np.random.seed(seed)
    return np.random.choice(label_list)


# Part 1

In [469]:

class Q1:

    def feature_means(self, banknote):
        features=banknote[:,:4]
        return np.mean(features,axis=0)

    def covariance_matrix(self, banknote):
        features=banknote[:,:4]
        return np.cov(features.T)

    def feature_means_class_1(self, banknote):
        data_class_1 = banknote[banknote[:,4] == 1, :4]
        return np.mean(data_class_1,axis=0)

    def covariance_matrix_class_1(self, banknote):
        data_class_1 = banknote[banknote[:,4] == 1, :4]
        return np.cov(data_class_1.T)


In [470]:
q1 = Q1()
q1.covariance_matrix_class_1(banknote)

array([[  3.53884798,   0.74923443,  -4.69053721,   1.26243851],
       [  0.74923443,  29.21276835, -25.24469813,  -5.69675942],
       [ -4.69053721, -25.24469813,  27.68665431,   3.00778701],
       [  1.26243851,  -5.69675942,   3.00778701,   4.28897428]])

In [471]:
# Q1. feature_means
def feature_means(self, banknote):
    features=self.banknote[:,:4]
    return np.mean(features,axis=0)

In [472]:
# Q2.covariance matrix 4*4 features
def covariance_matrix(self, banknote):
    features=self.banknote[:,:4]

    return np.cov(features.T)


In [473]:
#Q3 Feature means class 1
def feature_means_class_1(self, banknote):
    data_class_1 = banknote[banknote[:,4] == 1, :4]
    return np.mean(data_class_1,axis=0)

In [474]:
#Q4: Covariance matrix class 1
def covariance_matrix_class_1(self, banknote):
    return np.cov(data_class_1.T)

In [475]:
res=covariance_matrix(banknotes)
print(res)

TypeError: covariance_matrix() missing 1 required positional argument: 'banknote'

# Part 2

In [746]:
#Part 2- Q1
#implement Random
class HardParzen:
    def __init__(self, h):
        self.h = h
    def train(self, train_inputs, train_labels):
        self.label_list = np.unique(train_labels)
        self.label_length=len(np.unique(train_labels))
        self.train_inputs=train_inputs
        self.train_labels=train_labels
        print('training done')
    def compute_predictions(self, test_data):
        neighbours=[]
        
        length=test_data.shape[0]
        classes_pred=np.zeros(length)
        
        counts=np.ones((length,self.label_length))

        radius=self.h
        for i in range(0,len(test_data)):
            
            distance=(np.sum((np.abs(test_data[i] - self.train_inputs)) ** 2, axis=1)) ** (1.0 / 2)
            neighbours = np.array([j for j in range(len(distance)) if distance[j] < radius])
            print(neighbours)
            for k in neighbours:
                counts[i,int(self.train_labels[k]-1)]+=1
                print('Random')
            if max(counts[i,:])==1:
                classes_pred[i]=draw_rand_label(test_data[i],self.label_list)
            else:
                classes_pred[i] = np.argmax(counts[i, :])+1
        return classes_pred
         
         

In [756]:

f=HardParzen(0.5)
f.train(banknote[:10,:4],banknote[:10,4])
temp=f.compute_predictions(banknote[9:13,:4])
print(temp)

training done
[9]
Random
[]
[]
[]
[1. 0. 0. 0.]


In [757]:
banknote[:10,:4]

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645],
       [ 3.4566 ,  9.5228 , -4.0112 , -3.5944 ],
       [ 0.32924, -4.4552 ,  4.5718 , -0.9888 ],
       [ 4.3684 ,  9.6718 , -3.9606 , -3.1625 ],
       [ 3.5912 ,  3.0129 ,  0.72888,  0.56421],
       [ 2.0922 , -6.81   ,  8.4636 , -0.60216],
       [ 3.2032 ,  5.7588 , -0.75345, -0.61251],
       [ 1.5356 ,  9.1772 , -2.2718 , -0.73535]])

In [755]:
banknote[10:13,:4]

array([[ 1.2247 ,  8.7779 , -2.2135 , -0.80647],
       [ 3.9899 , -2.7066 ,  2.3946 ,  0.86291],
       [ 1.8993 ,  7.6625 ,  0.15394, -3.1108 ]])

In [562]:
banknote[1365:1371,:4]

array([[ -4.5046 ,  -5.8126 ,  10.8867 ,  -0.52846],
       [ -2.41   ,   3.7433 ,  -0.40215,  -1.2953 ],
       [  0.40614,   1.3492 ,  -1.4501 ,  -0.55949],
       [ -1.3887 ,  -4.8773 ,   6.4774 ,   0.34179],
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ]])

In [583]:
class ErrorRate:
    def __init__(self, x_train, y_train, x_val, y_val):
        self.x_train = x_train
        self.y_train = y_train
        self.x_val = x_val
        self.y_val = y_val

    def hard_parzen(self, h):
        knn_hard=HardParzen(h)
        print(knn_hard)
        knn_hard.train(self.x_train,self.y_train)
        knn_hard_pred=knn_hard.compute_predictions(self.x_val)

        n_classes = len(np.unique(knn_hard_pred))
        total_correct=0
        for i in range(0,len(knn_hard_pred)):
            if knn_hard_pred[i]==self.y_val[i]:
                total_correct+=1       
        total_pred=len(knn_hard_pred)        
        
        return (float(total_correct) / float(total_pred))
    
    def soft_parzen(self, sigma):
        pass
    
#         matrix = np.zeros((n_classes, n_classes))
#         for (true, pred) in zip(self.y_val, knn_hard_pred):
#             matrix[int(true - 1), int(pred - 1)] += 1

In [584]:
er=ErrorRate(train,train_label,test,test_label)
er.hard_parzen(10)

training done


1.0

In [541]:
test=banknote[5:10]
print(test)
test_label=test[:,4]

[[ 4.3684   9.6718  -3.9606  -3.1625   0.     ]
 [ 3.5912   3.0129   0.72888  0.56421  0.     ]
 [ 2.0922  -6.81     8.4636  -0.60216  0.     ]
 [ 3.2032   5.7588  -0.75345 -0.61251  0.     ]
 [ 1.5356   9.1772  -2.2718  -0.73535  0.     ]]


In [542]:
train=banknote[0:5]
train_label=train[:,4]


# Part 4

In [848]:
import math
class SoftRBFParzen:
    def __init__(self,sigma):
        self.sigma  = sigma
    def train(self, train_inputs, train_labels):
        self.label_list = np.unique(train_labels)
        self.label_length=len(np.unique(train_labels))
        self.train_inputs=train_inputs
        self.train_labels=train_labels
        


    def compute_predictions(self, test_data):
        neighbours=[]
        
        length=test_data.shape[0]
        classes_pred=np.zeros(length)
        counts=np.ones((length,self.label_length))
        for i in range(len(test_data)):
            distances = (np.sum((np.abs(test_data[i] - self.train_inputs)) ** 2, axis=1)) ** (1.0 / 2)
            dic = dict.fromkeys(self.label_list, 0)
            for j in range(len(distances)):
                sig=(1/(np.sqrt(2*np.pi)*self.sigma))*np.exp(-(distances[j]**2/(2*self.sigma**2)))*100
                
                dic[self.train_labels[j]]+=float(sig)
                print(dic,sig,self.train_labels[j])
            
            classes_pred[i]= max(dic, key=dic.get)
            print(classes_pred[i])
            print('break')
        return classes_pred

            
            
            

In [863]:
from sklearn.datasets import load_iris
from sklearn.neighbors.kde import KernelDensity
import numpy as np

X, y = load_iris(return_X_y=True)

In [881]:
estimators = []
for c in [0, 1]:
    m = KernelDensity().fit(x_train[x_test == c])
    estimators.append(m)
    
for estimator in estimators:
    print(estimator.score_samples([x_train]))

ValueError: Found array with dim 3. Estimator expected <= 2.

In [875]:
banknote=np.array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])
validation=np.array(   [    [  1.5356  ,   9.1772  ,  -2.2718  ,  -0.73535 ,   0.      ],
#        [  3.404   ,   8.7261  ,  -2.9915  ,  -0.57242 ,   0.      ],
#        [  0.066129,   2.4914  ,  -2.9401  ,  -0.62156 ,   1.      ],
       [ -2.8391  ,  -6.63    ,  10.4849  ,  -0.42113 ,   1.      ],
       [ -3.7503  , -13.4586  ,  17.5932  ,  -2.7771  ,   1.      ]])
s=SoftRBFParzen(0.2)
x_train=banknote[: ,:4]
x_test=banknote[:,4]
s.train(x_train,x_test)
s.compute_predictions(validation[:,:4])

{0.0: 1.7836467778376577e-25, 1.0: 0} 1.7836467778376577e-25 0.0
{0.0: 1.7836467778376577e-25, 1.0: 0} 3.261413259539294e-56 0.0
{0.0: 1.7836467778376577e-25, 1.0: 0} 0.0 0.0
{0.0: 1.7836467778376577e-25, 1.0: 0.0} 0.0 1.0
{0.0: 1.7836467778376577e-25, 1.0: 0.0} 0.0 1.0
{0.0: 1.7836467778376577e-25, 1.0: 0.0} 0.0 1.0
0.0
break
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 0.0} 0.0 1.0
{0.0: 0.0, 1.0: 9.592395121727099e-42} 9.592395121727099e-42 1.0
{0.0: 0.0, 1.0: 9.592395121727099e-42} 0.0 1.0
1.0
break
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 0} 0.0 0.0
{0.0: 0.0, 1.0: 199.47114020071635} 199.47114020071635 1.0
{0.0: 0.0, 1.0: 199.47114020071635} 2.0387748412929085e-297 1.0
{0.0: 0.0, 1.0: 199.47114020071635} 0.0 1.0
1.0
break


array([0., 1., 1.])

In [667]:
x_test

array([0., 0., 0., 1., 1., 1.])

In [665]:
import numpy as np
import matplotlib.pyplot as plt
N=30
sigma=1
T=np.linspace(1,N,N)
n=30
X=np.random.normal(0, sigma, 1000)
x=1
alpha=0.45

def k_gaussien(x,sigma): #kernel gaussien
    if(sigma<=0):
        return((1/(sigma*sqrt(2*pi)))*exp(-(x**2/(2*sigma**2))))

# def h(n,alpha): #bandwith
#     h=np.ones((1,1))
#     for i in range(2,N):
#         h[i]= h[i-1] + (i**(-alpha))

def f_PR(x,X,sigma): #Parzen-Rosenblatt estimator (f_PR)
    global F;
    F = np.zeros((N,0));
    for k in range(2,N):
        for i in  range(1,k):
            F[k] = F[k-1] + k_gaussien((x-X[i]),1);
        F[k] = F[k-1] 
    print(F);

# almost surely convergency
fPR=f_PR(x,X,sigma)


[]


In [533]:
train_label

array([0., 0., 0., 0., 0.])

In [534]:
x=np.array([[1,2],[3,4]])

In [535]:
sigma=1
sig=(1/(np.sqrt(2*np.pi)*sigma))*np.exp(-(x**2/(2*sigma**2)))
print(sig)

[[2.41970725e-01 5.39909665e-02]
 [4.43184841e-03 1.33830226e-04]]


In [536]:
sigma=1
x=
print((1/(sigma*np.sqrt(2*np.pi)))*np.exp(-(x**2/(2*sigma**2))))

SyntaxError: invalid syntax (<ipython-input-536-daf24b7c0410>, line 2)

In [656]:
banknote

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [537]:
for i in range(len(test_data)):
    distance=(np.sum((np.abs(test_data[i] - self.train_inputs)) ** 2, axis=1)) ** (1.0 / 2)
    

NameError: name 'test_data' is not defined

# Part - 4 Split Dataset


In [538]:
def split_dataset(banknote):
    length=list(range(0,len(banknote)))
    train_index=[]
    validation_index=[]
    test_index=[]
    
    for i in range(0,len(length)):
        if i%5==0 or i%5==1 or i%5==2:
            train_index.append(i)
        elif i%5==3:
            validation_index.append(i)
        elif i%5==4:
            test_index.append(i)
    train=banknote[train_index]
    validation=banknote[validation_index]
    test=banknote[test_index]
#     print(len(train),len(validation),len(test))
    return (train,validation,test)
    


In [341]:
temp=split_dataset(banknote)
print(temp)

824 274 274
(array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645,  0.     ],
       ...,
       [ 0.40614,  1.3492 , -1.4501 , -0.55949,  1.     ],
       [-3.5637 , -8.3827 , 12.393  , -1.2823 ,  1.     ],
       [-2.5419 , -0.65804,  2.6842 ,  1.1952 ,  1.     ]]), array([[ 3.4566e+00,  9.5228e+00, -4.0112e+00, -3.5944e+00,  0.0000e+00],
       [ 3.2032e+00,  5.7588e+00, -7.5345e-01, -6.1251e-01,  0.0000e+00],
       [-1.5768e+00,  1.0843e+01,  2.5462e+00, -2.9362e+00,  0.0000e+00],
       ...,
       [-1.0116e+00, -1.9038e-01, -9.0597e-01,  3.0030e-03,  1.0000e+00],
       [-1.1667e+00, -1.4237e+00,  2.9241e+00,  6.6119e-01,  1.0000e+00],
       [-1.3887e+00, -4.8773e+00,  6.4774e+00,  3.4179e-01,  1.0000e+00]]), array([[  0.32924 ,  -4.4552  ,   4.5718  ,  -0.9888  ,   0.      ],
       [  1.5356  ,   9.1772  ,  -2.2718  ,  -0.73535 ,   0.      ],
       [  3.404   ,   8

In [333]:
li=[3,8,13]
temp=banknote[li]
print(temp)

[[ 3.4566   9.5228  -4.0112  -3.5944   0.     ]
 [ 3.2032   5.7588  -0.75345 -0.61251  0.     ]
 [-1.5768  10.843    2.5462  -2.9362   0.     ]]


In [317]:
banknote[0:10]

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699,  0.     ],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ,  0.     ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645,  0.     ],
       [ 3.4566 ,  9.5228 , -4.0112 , -3.5944 ,  0.     ],
       [ 0.32924, -4.4552 ,  4.5718 , -0.9888 ,  0.     ],
       [ 4.3684 ,  9.6718 , -3.9606 , -3.1625 ,  0.     ],
       [ 3.5912 ,  3.0129 ,  0.72888,  0.56421,  0.     ],
       [ 2.0922 , -6.81   ,  8.4636 , -0.60216,  0.     ],
       [ 3.2032 ,  5.7588 , -0.75345, -0.61251,  0.     ],
       [ 1.5356 ,  9.1772 , -2.2718 , -0.73535,  0.     ]])

In [829]:
vec1=np.array([1,1,1])
mat=np.array([[5,3,3],
            [8,4,4],[50,5,5],[100,100,100]])

In [830]:
abs(vec1-mat)

array([[ 4,  2,  2],
       [ 7,  3,  3],
       [49,  4,  4],
       [99, 99, 99]])

In [831]:
def minkowski_mat(x, Y, p=2):
    return (np.sum((np.abs(x - Y)) ** p, axis=1)) ** (1.0 / p)
distances = minkowski_mat(vec1,mat)
print(distances)

[  4.89897949   8.18535277  49.32544982 171.47302995]


In [832]:
from statistics import NormalDist

import scipy.stats
for i in distances:
    print(NormalDist(mu=0, sigma=0.5).pdf(i), scipy.stats.norm(0, 1).pdf(i))

1.1371164182297778e-21 2.4511860875074138e-06
5.08720790059514e-59 1.1273140559828679e-15
0.0 0.0
0.0 0.0
